### ISSUE TITLE
Action icons

### ISSUE THREAD

**Issue by DaveJ61** [Rythal/Carbonite#123]
I have found this morning that the action icons against certain quests do not work.
For instance I had a quest called "Tricks of the Trade" - "Trader Roused", where you had to douse the trader with a mug of coffee. The icon beside the quest did not work when left or right clicking it. However, I had to use my qbar addon to complete the quest (or I could have used the blizzard quest dialog).
Whether this was an isolated case, I am not yet sure but I will check and report further findings.

Incidentally, how do I report quests that are missing from the database? For instance I have completed a quest "The Clarity Elixir" but on returning to where I am directed by Carbonite at The Twilight Glade, he is not there. He is actually at Moonwillow Peak, not the question mark on the map. However, I don't think this is Carbonite as the blizzard gui has it wrong also. After looking on wowhead, the entrance to path that leads to Moonwillow peak is at 41.0, 53.6, and Velen is at 35.3, 49.1.

**Comment by atk** [comment]
ircdirk and I prepared an option for Carbonite.Quest to collect the data. We'll create an aggregator next.

**Comment by atk** [comment]
The aggregator is up and running: http://atk.github.io/Carbonite/#upload
