### ISSUE TITLE
Quest watch Color Objective based on progress.

### ISSUE THREAD

**Issue by DaveJ61** [Rythal/Carbonite#137]
This setting does not appear to be working. It was working nicely before WoD.
Screen shot attached. The topmost quest is a third the way through but is still deep red, same as incomplete. It used to gradually work its way to green but will only turn green when fully completed.
 
![carbonite1](https://cloud.githubusercontent.com/assets/1816367/5528385/9c61a60a-89ff-11e4-8fe8-972042f78367.jpg)

**Comment by atk** [comment]
This is supposed to be fixed by https://github.com/Rythal/Carbonite/commit/e2b3b2a03473b936d007434256eb57db543b928b

**Comment by atk** [comment]
I have confirmed that the fix works.
