### ISSUE TITLE
Carbonite.Warehouse: Double entries for Chars from same realm Connected realms Issue

### ISSUE THREAD

**Issue by samyonair** [Rythal/Carbonite#139]
Hi 

There is a Problem with Chars from same realm in Warehousemodlue on  Connected realms
all chars, on the realm your currently on apart of the One your on with are doubled, think comes from connected realms fix, My Idea a locale for current realm and that locale "current" as is not current added to the fix could help

Greetings Samyonair

Link to Forum:

http://www.wowinterface.com/forums/showthread.php?t=50850

**Comment by atk** [comment]
This problem is fixed by Rythals latest fixes.
