### ISSUE TITLE
NxQuest.lua:4428: assertion failed

### ISSUE THREAD

**Issue by VOiDProXy** [Rythal/Carbonite#144]
Hi, this is the first time I am filling out a bug report on GitHub so please point me in the right direction if you need anything or if I'm simply doing it wrong:

I received this error when right-clicking the quest tracker and left-clicked to stop tracking an achievement.
I have removed all my saved variables of carbonite and did a fresh clone to make sure I am running the latest.

`Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:4428: assertion failed!
Time: 12/25/14 18:18:09
Count: 1
Stack: (tail call): ?
[C]: ?
[C]: in function `assert'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:4428: in function `FindCurByIndex'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:4413: in function `FindCur'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:8302: in function `RemoveWatch'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:8242: in function `Func'
Interface\AddOns\Carbonite\NxUI.lua:4758: in function <Interface\AddOns\Carbonite\NxUI.lua:4728>

Locals: (*temporary) = "LeftButton"
(*temporary) = <function> defined =[C]:-1`

**Comment by atk** [comment]
Added a few more comparisons so no negative quest id should ever be searched.
