### ISSUE TITLE
...Locales\itIT\Options.lua line 283 error

### ISSUE THREAD

**Issue by Morindra** [Rythal/Carbonite#207]
This error popped on login.

Date: 2015-01-01 12:53:14
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\Locales\itIT\Options.lua line 283:
   unfinished string near '"'
Debug:
   
Locals:

AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  AckisRecipeList, v3.0.12
  Carbonite, v6.0.1
  LibSharedMedia30, v3.0-89
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=a4)

**Comment by samyonair** [comment]
Fixed by commit 5a55fc79008d0eb9c96502fcce4f8f9e34f6c32c

**Comment by mlande5** [comment]
The error was still occurring as of 1 hour ago. How can it be fixed with the update from this morning?

**Comment by mlande5** [comment]
correction did fresh install issue resolved. Thank you,
