### ISSUE TITLE
comprehension Problem Instance Scenario Questwatchlist

### ISSUE THREAD

**Issue by samyonair** [Rythal/Carbonite#216]
In Instances 

The Tasks are named Bonus and the Complete Information isn't shown if it's done

Issue seems to be in NxQuest.lua
line 8699-8713 
local bonusSteps = C_Scenario.GetBonusSteps()
						if bonusSteps then
							local title, task, _, completed = C_Scenario.GetStepInfo(1)
							local tasktexts = { "Bonus |cff00ff00" }
							task:gsub('%S+%s*', function(word)
								if (#tasktexts[#tasktexts] + #word) < (Nx.qdb.profile.QuestWatch.OMaxLen + 10) then
									tasktexts[#tasktexts] = tasktexts[#tasktexts] .. word
								else
									tasktexts[#tasktexts+1] = " |cff00ff00" .. word
								end
							end)
							tasktexts[1] = " |cffff0000" .. tasktexts[1]
							if completed then
								tasktexts[#tasktexts] = tasktexts[#tasktexts] .. " |cffff0000[|cffffffff" ..L["Complete"] .."|cffff0000]"
							end

Greetings Samyonair

see forum http://www.wowinterface.com/forums/showthread.php?t=51395

**Comment by samyonair** [comment]
local tasktexts = { "Bonus |cff00ff00" } should be changed to { L["Task: |cff00ff00"] }
from my comprehension it is a Information what to do but Problem also is that the Complete Information doesn't work 
line numbers can defer because of open PR

**Comment by atk** [comment]
I know that lines because I have written them, but I only added line handling for bonus tasks... I'll have a look into it later.

**Comment by samyonair** [comment]
Have edited my prouvious post with links, these works for Information in dungeons, too and Bonus is here a Problem

**Comment by atk** [comment]
I'll try to make a distinction.

**Comment by atk** [comment]
The error was there before. The code I wrote was for bonus steps, but this gets the infos for the first quest instead of the bonus steps alone...

**Comment by atk** [comment]
Fixed by latest push; now only the bonus quest will be shown in this part of the code.
