### ISSUE TITLE
Battleground Maps Not Working

### ISSUE THREAD

**Issue by greenmig** [Rythal/Carbonite#227]
Hello,

ty for your great work with this addon.  i only have a small request.  i play alot of bg's however i notice that not all of them display their maps correctly.  some are ok like mines, wsg, ab, eots however others such as dwg do not work at all.  carbonite does not pick them up.  can you please check them and make them all work.

ty

**Comment by IrcDirk** [comment]
Its fixed in GitHub version, download it.

**Comment by greenmig** [comment]
Oh in latest version at https://github.com/Rythal/Carbonite?

Ty man
