### ISSUE TITLE
AceLocale-3.0: Carbonite.Warehouse Errors

### ISSUE THREAD

**Issue by LargeGoose** [Rythal/Carbonite#234]
I'm getting loads of errors from what appears to be the Warehouse module. The fact that I can't find it in the issues list (open or closed) makes me think it is something I'm doing wrong but I cannot find a solution.

Message: AceLocale-3.0: Carbonite.Warehouse: Missing entry for '%s|cFFFF0000[|cFF00FF00Mail:%d|cFFFF0000]'
Debug:
   Carbonite.Warehouse\NxWarehouse.lua:1540: FindCharsWithItem()
   Carbonite.Warehouse\NxWarehouse.lua:1753:
      Carbonite.Warehouse\NxWarehouse.lua:1731
   [C]: ?
   [C]: SetBagItem()
   ..\FrameXML\ContainerFrame.lua:1059: ContainerFrameItemButton_OnEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1

Message: AceLocale-3.0: Carbonite.Warehouse: Missing entry for '%s (%s Mail)'
Debug:
   Carbonite.Warehouse\NxWarehouse.lua:1529: FindCharsWithItem()
   Carbonite.Warehouse\NxWarehouse.lua:1753:
      Carbonite.Warehouse\NxWarehouse.lua:1731
   [C]: ?
   [C]: SetBagItem()
   ..\FrameXML\ContainerFrame.lua:1059: ContainerFrameItemButton_OnEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1

Message: AceLocale-3.0: Carbonite.Warehouse: Missing entry for '%s|cFFFF0000[|cFF00FF00Bank:%d|cFFFF0000]'
Debug:
   Carbonite.Warehouse\NxWarehouse.lua:1543: FindCharsWithItem()
   Carbonite.Warehouse\NxWarehouse.lua:1753:
      Carbonite.Warehouse\NxWarehouse.lua:1731
   [C]: ?
   [C]: SetBagItem()
   ..\FrameXML\ContainerFrame.lua:1059: ContainerFrameItemButton_OnEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1

Are three examples of what I'm seeing in swatter. There are lots of others that aren't FindCharsWithItem() but they are the most frequent. Basically after login if I mouse over most things that have an icon and are an item I get an error.

**Comment by samyonair** [comment]
What locale your Game Client is running or better on which language your game runs? it is a localisation Issue

**Comment by gOOvER** [comment]
Which Language?


Am 7. Januar 2015 00:15:41 schrieb LargeGoose <notifications@github.com>:

**Comment by LargeGoose** [comment]
System -> Language is set to English, where else might there be a setting? As an FYI I just logged in and when mouse over the Carbonite enhance mini map I get:-

Message: AceLocale-3.0: Carbonite: Missing entry for 'yds'
Debug:
   Carbonite\NxMap.lua:3882:
      Carbonite\NxMap.lua:3725

What is intersting is that I appear to also be getting errors on code comments like:-

Date: 2015-01-07 09:24:32
ID: 17
Error occured in: Global
Count: 1
Message: AceLocale-3.0: Carbonite: Missing entry for 'frFR - powerstrk'
Debug:
   Carbonite\NxOptions.lua:187:
      Carbonite\NxOptions.lua:161
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:310: app()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1803: Open()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1896:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1894
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[2]"]:9:
      [string "safecall Dispatcher[2]"]:5
   (tail call): ?
   Ace3\AceGUI-3.0\AceGUI-3.0.lua:314: Fire()
   ...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:20:
      ...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19
   [C]: Show()
   ..\FrameXML\InterfaceOptionsFrame.lua:28: InterfaceOptionsList_DisplayPanel()
   ..\FrameXML\InterfaceOptionsFrame.lua:46: InterfaceOptionsListButton_OnClick()
   ..\FrameXML\InterfaceOptionsFrame.lua:475: InterfaceOptionsFrame_OpenToCategory()
   Carbonite\NxOptions.lua:4136: Open()
   Carbonite\NxMap.lua:2867: Func()
   Carbonite\NxUI.lua:4904:
      Carbonite\NxUI.lua:4874

Time to remove all addons and start again?

**Comment by atk** [comment]
Have you tried to update your version of carbonite?

**Comment by samyonair** [comment]
We both meant your game client settings, but if you play on an english PC I would think you use a english client please reinstall carbonite and check that all locales files are installed for english
for example {Path to WOW}\World of Warcraft\Interface\CArbonite.Warehouse\Locales\enUS.lua

It seems that your Locales files are corrupted

greetings Samyonair

**Comment by LargeGoose** [comment]
The Battle.net client language setting is English (UK) rather than English (US). ~Warehouse\Locales\enUS.lua is only 44 lines long and is missing lines 21 and 46 from the current GitHUb version (and everything from line 48 onwards. I'll pull down the latest and sync. Should I need to copy enUS.lua to enUK.lua or does UK default to US if missing?

**Comment by atk** [comment]
Yes, enUS is also for other english speakers; we don't have a UK version.
