### ISSUE TITLE
BUG:Carbonite.Quests\NxUI..lua:2792

### ISSUE THREAD

**Issue by Haggisdog** [Rythal/Carbonite#235]
When trying to move/resize the map this message is displayed:

 Interface\AddOns\Carbonite\NxUI.lua:2792: Frame NxMap1 is not resizable
Time: 01/06/15 18:16:13
Count: 1
Stack: [C]: in function `StartSizing'
Interface\AddOns\Carbonite\NxUI.lua:2792: in function <Interface\AddOns\Carbonite\NxUI.lua:2766>

**Comment by IrcDirk** [comment]
Include list of addons and with version of Carbonie you are using (Live or GitHub).

**Comment by samyonair** [comment]
Close this because of missing information can be reopend if Information is given
