### ISSUE TITLE
NxSocial - Punks error spam (attempt to index local 'punk')

### ISSUE THREAD

**Issue by VOiDProXy** [Rythal/Carbonite#236]
Getting a complete overload of messages when Stormshield was under attack by a local rival faction band of ruffians:

Message: Interface\AddOns\Carbonite.Social\NxSocial.lua:1779: attempt to index local 'punk' (a nil value)
Time: 01/07/15 04:37:06
Count: 447
Stack: (tail call): ?
(tail call): ?
Interface\AddOns\Carbonite.Social\NxSocial.lua:1779: in function `AddLocalPunk'
Interface\AddOns\Carbonite.Social\NxSocial.lua:2705: in function `?'
...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[16]"]:4: in function <[string "safecall Dispatcher[16]"]:4>
[C]: ?
[string "safecall Dispatcher[16]"]:13: in function `?'
...vUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...face\AddOns\ElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...face\AddOns\ElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by atk** [comment]
Cannot reproduce that error anymore.

**Comment by VOiDProXy** [comment]
I no have a sneaking suspicion it was a temporary thing with ElvUI. Thanks for looking at it though.
