### ISSUE TITLE
Strange issue when I loggon in a character

### ISSUE THREAD

**Issue by Thrumbar** [Rythal/Carbonite#246]
After I logged in to one of my alts and accepted the fly to stormshield quest from my garrison.  Upon going there and turning it in and getting the next quest the quest tracker arrow went strange.

http://youtu.be/-0ZtYRmQhgA

A reset fixed it but this was the first time it happened to me.
Using the latest git as of 01/08/2015.

**Comment by IrcDirk** [comment]
Is this similar to this issue https://github.com/Rythal/Carbonite/issues/89 ? Please write us which version of carbonite u are using and please list your addons.

**Comment by Thrumbar** [comment]
Is this similar to this issue #89 ?
I would say no as the arrow does not move at all, just the countdown like circular pattern.

Please write us which version of carbonite u are using and please list your addons.
As I have posted, I have downloaded the Git on 01/08/2015 which with the exception of the recent commit " small fix for error in instances" 12 Hours ago as of this reply is the current git.  The Toc info for carbonite below with list of other addon after. 

Carbonite 6.0.1
Carbonite Info 1.0
Carbonite Items 1.1
Carbonite Notes 1.1
Carbonite Quest 1.0
Carbonite Social & Punks 1.0
Carbonite Warehouse 1.0
Carbonite Weekly 1.0

Buggrabber
Cursor
Altoholic
Autobar
Bagon
Brokermounts
Bugsack
Dugi Questing Essential
GarrisonCommander
Grid2
Guild Tithe
Hunter Pets
Hydra
Ion
MikScrollingBattleText
Pet Selector
PitBull Frames 4.0
Postal
Prat 3
Raven
TipTac
Titan Panel
Titan Panel Garrison Recources
WoWDB Profiler

**Comment by IrcDirk** [comment]
Your youtube movie is private we cant watch it.

**Comment by Thrumbar** [comment]
Fixed link

**Comment by IrcDirk** [comment]
Yep thats weird, cant reproduce :(

**Comment by deathcore01** [comment]
i have the same issue, is a bug in cunjunction with dugi guides - i have fixed it in my local copy, i will see that it's okay if i doing this, i must rename the function + the calls from SetMapByID, changed by rhytal and now the function will work, where rhytal have think without the issue.
