### ISSUE TITLE
Dungeon maps broken again

### ISSUE THREAD

**Issue by Ghosthree3** [Rythal/Carbonite#248]
Finally downloaded the latest push and replaced my release copy from curse. I'm in Naxxramas and the minimap is a blank blur while the full map is showing a full sized copy of the 'first' floor.

**Comment by atk** [comment]
Duplicate of #186

**Comment by Ghosthree3** [comment]
Not a duplicate because changes were made based on that issue, then this happened. Unless I'm way out of the loop.

**Comment by atk** [comment]
There were changes made, yes, but they only partly improved the situation. You'll note that the issue is not yet closed, unlike this one.

**Comment by IrcDirk** [comment]
There ware fixes but the issue was not fixed ;)
