### ISSUE TITLE
Carbonite not joining public Carbonite chat channels

### ISSUE THREAD

**Issue by VOiDProXy** [Rythal/Carbonite#251]
Not sure if this will be a proper issue report so please feel free to close this issue as you see fit, I'm happy to provide any additional info when I get back into Azeroth. Also, please forgive my autocorrect if something sounds funny, I will clarify.

I am filing this issue because I'm having trouble getting my Carbonite to chat and sync with other Carbonite users. When I go to see which chat channels that I have joined nothing except the chat channels I have set up show in the list, no CarbZ*** (I believe is the format) listed at all. I really love love love Carbonite's social feature especially for playing on a PvP and getting a heads up on where those pesky punks are right now so I can either steer clear or head there.

I have tried running Carbonite only, deleting all Carbonite and Carbonite module's savedvariables, tried switching the social settings under privacy off, reloaded my UI and switching them back on again without success.

Some of my alts have had the function working a week or two ago. I saw chat channels with people in them on my server. Was this taken out recently or is there something else?

**Comment by samyonair** [comment]
Do you have installed Carbonite social Module? Carbonite is now modularized.. And Punk sync is in social module as i know Greetings samyonair

**Comment by VOiDProXy** [comment]
Yep, Carbonite Social is installed enabled and running, have all the options to enable or disable the chat channels, Carbonite just doesn't seem to want to join any channels.

**Comment by IrcDirk** [comment]
No problem on my side:
http://i.imgur.com/YXMfWkE.png
but this two options have to be enabled:
http://i.imgur.com/42udqmy.png

Other thing is if u are on 10 channels u cant join more, so check that too.

**Comment by VOiDProXy** [comment]
Thanks - I'll log into my priest with nothing but carbonite and see if the problem is still there.

**Comment by VOiDProXy** [comment]
Nope - nothing wrong here. Probably just a conflict with ElvUI or something. Next time I'll do the same thing move out all the addons except blizz and carbonite and see if it's still bugged before I come running to GitHub.
