### ISSUE TITLE
Guide arrow sliding off screen

### ISSUE THREAD

**Issue by Ghosthree3** [Rythal/Carbonite#259]
Every now and then I have to do a /carb resetwin because the arrow will literally slide sideways off screen and I can't get it back.

I THINK it only happens if I'm riding past something and get into combat, but it doesn't happen every time so I can't be sure.

**Comment by deathcore01** [comment]
can you make screenshots or a video and give a list of your addons? this can help to reproduce this issue.

**Comment by Ghosthree3** [comment]
It's rare enough that I'd have to be recording 3-6 hours of questing. I guess I could do that later then cut it. Screenshots won't help, or rather I can't see how, that'd just be a screenshot of it half way off the screen.

Addons are:
Adibags
Auctionator
Carbonite
DBM
GatherMate
Wholly & Grail
Grid
Master Plan
MikScrollingBattleText
Overachiever
Recount
SPTimers
Target Health Percent
Tidy Plates
TSM + all modules
WeakAuras 2

However it was happening when I only had:
Carbonite
DBM
Grid
Recount
SPTimers
WeakAuras 2

**Comment by SteveEbey73742** [comment]
https://github.com/Rythal/Carbonite/issues/89 is the original report of this issue, check there for updates, or to post more information.

**Comment by IrcDirk** [comment]
Duplicate issue!

**Comment by samyonair** [comment]
because of dublicate to #89 closed
