### ISSUE TITLE
Cannot unselect Autotrack Taxi in TrackingHud settings

### ISSUE THREAD

**Issue by Thrumbar** [Rythal/Carbonite#260]
When I go into the hud settings I cannot uncheck Auto Track Taxi Destination
As a check I downloaded the latest git  as of commit 8275b4f151cb158d828691efe546ef1e2df832b0.
Merge pull request #258 from ThorwaldOdin/master.

Downloaded 01/18/2015 2:20am (Only have Carbonite installed)

Edit: Each time I click on the checkbox to try to cleat is the tracking hud flickers.
Edit 2: Issue was reported previously - 
     http://www.wowinterface.com/forums/showthread.php?t=46743&highlight=taxi
Edit 3: Can change it only by editing Carbonite\carbonite.lua line 456 changing "true" to "false". Cannot change it in the options.

**Comment by atk** [comment]
https://github.com/Rythal/Carbonite/blob/DEV/Carbonite/NxOptions.lua#L3956 - small typo: "ATtaxi" is meant to be "ATTaxi".

**Comment by atk** [comment]
Fixed in DEV branch.

**Comment by Thrumbar** [comment]
Ok. when will it be included on Git as of this it has not.
