### ISSUE TITLE
Dalaran map still in the middle of nowhere

### ISSUE THREAD

**Issue by Ghosthree3** [Rythal/Carbonite#276]
Title, it isn't placed properly within Northrend which makes waypoints out of or into Dalaran useless.

**Comment by IrcDirk** [comment]
Cant reproduce. No problems with Dalaran map on my side.

**Comment by Ghosthree3** [comment]
There's no reproduce required, it's permanent, see here.

Map missing from location here - I'm hovering where it should be with mouse and it's not showing it like it does for every other city:
http://i.imgur.com/UYAvdrj.png

Map is actually here:
http://i.imgur.com/C8zdBjs.png

Way point out of Dalaran when inside it:
http://i.imgur.com/Z6VRaKh.png

Way point to Dalaran when out of it:
http://i.imgur.com/ZUW8lNl.png

**Comment by IrcDirk** [comment]
I got no problem with it, my map is ok ;)

**Comment by Ghosthree3** [comment]
Strange, I've had this issue since November. Still there now in latest Curse release.

**Comment by IrcDirk** [comment]
Ok i get the point now... its related to waypoints ... Dalaran is placed on map the same way as instances, this is know issue. Waypoints needs to be rewriten.

**Comment by Ghosthree3** [comment]
Why not just fix it so it operates like every other map - eg. Orgrimmar - and is located where it actually is on the map.

**Comment by IrcDirk** [comment]
For me the map is in the place it should be thants on Northend in Crystalsong Forest, only waypoints from Dalaran doesnt work.

**Comment by IrcDirk** [comment]
Ok seems i did haved other version on my PC, confirm latest Master has this issue. Seems something with overlay map overlay map (Crystalsong is overlay and on it we should draw overlay with Dalaran). Something must have changed.

**Comment by IrcDirk** [comment]
The Underbelly in Dalaran also doesnt work. 

This problem reffers to NxMapData.lua the part:

Map.MapLevels={}

seems its not used any more but for overlays over overlays it should be implement.

**Comment by IrcDirk** [comment]
Please try this DEV release => https://github.com/Rythal/Carbonite/archive/DEV.zip

**Comment by Ghosthree3** [comment]
Dalaran is now in place.
