### ISSUE TITLE
Weird Quest watch window

### ISSUE THREAD

**Issue by Thrumbar** [Rythal/Carbonite#283]
Logged in and was surprised by the following.

https://onedrive.live.com/redir?resid=50E237CE0C7C122F!12439&authkey=!APZvGpew_vP1O5o&v=3&ithint=photo%2cjpg
https://onedrive.live.com/redir?resid=50E237CE0C7C122F!12636&authkey=!AAaFVELUw7_PPEo&v=3&ithint=photo%2cpng

Bonus Bonus Bonus  with repeating mobs to kill

This applies to just about every instance I have entered.

**Comment by samyonair** [comment]
fIXED
