### ISSUE TITLE
Sound Fix

### ISSUE THREAD

**Issue by SteveEbey73742** [Rythal/Carbonite#284]
Change .wav to .ogg and all the sound files work now, have a commit from my clone copy on my computer, but do not have permission to push.  NXoptions.lua is the file to change.

**Comment by nelegalno** [comment]
Files linking to .WAV files:
**Carbonite\NxMap.lua
Carbonite\NxOptions.lua
Carbonite.Social\NxSocial.lua**

**Comment by SteveEbey73742** [comment]
do you want me to do the changes, or are you?  I would need permission to sync with master, since that is what I have cloned on my desktop github

**Comment by nelegalno** [comment]
Fixed by Rythal in b251b24293aca848b56e290c318673413f89c057
