### ISSUE TITLE
Alliance - Talador - Swatter Error

### ISSUE THREAD

**Issue by Aldavor** [Rythal/Carbonite#291]
Quest: Destination Unknown (34154)
On entering the portal to fight Mongrethod; following Swatter error:
<code>
Date: 2015-04-05 17:42:02
ID: -1
Error occured in: Global
Count: 19
Message: ..\AddOns\Carbonite\NxMap.lua line 6493:
   attempt to perform arithmetic on a nil value
Debug:
   Carbonite\NxMap.lua:6493: UpdateOverlay()
   Carbonite\NxMap.lua:6324: UpdateZones()
   Carbonite\NxMap.lua:4574: Update()
   Carbonite\NxMap.lua:3820:
      Carbonite\NxMap.lua:3735
Locals:
self = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 PlyrRZY = 73.267149925232
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 351.5046995028
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.71111112833023
 Zone = 0
 WorldAlpha = 0
 StartupShown = true
 ScaleDraw = 4
 BackgndAlphaFade = 0.4
 MoveLastX = -2296.796216533
 PlyrDir = 351.5046995028
 PlyrSpeedCalcTime = 5252.931
 MapPosYDraw = -3603.3605255598
 PlyrSpeed = 0
 MapScale = 0.39920159680639
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 232.80032348633
 MMGathererUpdateDelay = 1
 MMAddonFrms = <table> {
 }
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 213.99995422363
 MMScales = <table> {
 }
 MMArrowName = "Interface\Minimap\MinimapArrow"
 MapPosX = -2296.796216533
 BackgndAlphaTarget = 0.4
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.67
 H = 141
 Tick = 36819
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -3603.3605255598
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = -2296.796216533
 QuestAlpha = 0.3
 CurWorldUpdateOverlayNum = 1
 MMFScale = 0.4
 Scale = 4
 Targets = <table> {
 }
 BackgndAlpha = 0.4
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = -1
 MMOwn = true
 MMModels = <table> {
 }
 Size1 = 1.0546874744614
 ShowUnexplored = false
 Arch = <unnamed> {
 }
 PIconMenu = <table> {
 }
 WorldHotspotTipStr = "Draenor, Talador (94-96)
"
 LocTipFrm = NxMapTip {
 }
 IconFrms = <table> {
 }
 StepTime = 0
 PlyrSpeedX = -2296.796216533
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.1
 ScaleDrawW = 0.25
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 CurOverlaysTexFolder = "talador"
 MiniFrms = <table> {
 }
 InCombat = false
 TrackDistYd = 9.6733178597743
 TrackName = "Retribution Point, Talador"
 Win = <table> {
 }
 InstanceId = false
 RealScale = 4
 Data = <table> {
 }
 TrackDir = false
 MMMaskName = "Interface\Buttons\White8x8"
 BGIconMenu = <table> {
 }
 CurOverlays = <table> {
 }
 TrackETA = false
 MMZoomChanged = false
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 MMScale = 4
 MMZoomType = 0
 TextScFrm = <unnamed> {
 }
 Indoors = true
 GIconMenuIFindNote = <table> {
 }
 TextFrm = <unnamed> {
 }
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 MapPosY = -3603.3605255598
 PlyrY = -3603.3605255598
 TargetNextUniqueId = 1
 Tracking = <table> {
 }
 Cont = 90
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Level = 17
 W = 150
 CurWorldUpdateMapId = 946
 MapsDrawnFade = <table> {
 }
 DotRaidScale = 1
 ContFrms = <table> {
 }
 PlyrSpeedY = -3603.3605255598
 TileFrms = <table> {
 }
 ScaleW = 0.25
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 MMAlphaDelay = 0
 MMOwnedFrms = <table> {
 }
 MMChkDelay = 2
 ArchAlpha = 0.3
 MapIndex = 1
 MapPosXDraw = -2296.796216533
 PlyrRZX = 31.016355752945
 KillShow = false
 MenuIMonitorZone = <table> {
 }
 NeedWorldUpdate = false
 TransMenu = <table> {
 }
 GIconMenu = <table> {
 }
 Frm = <unnamed> {
 }
 DotZoneScale = 1
 MoveDir = 180
 BackgndAlphaFull = 1
 DotPalScale = 1
}
mapId = -1
bright = 1
noUnexplored = nil
wzone = <table> {
 1 = 1
 2 = 0
 3 = 0
}
txFolder = "talador"
overlays = <table> {
 fortwrynn = "567,42,292,235"
 aruuna = "597,178,389,234"
 shattrath = "173,22,406,367"
 centerisles = "546,228,252,280"
 seentrance = "685,298,308,276"
 tuurem = "472,148,225,224"
 auchindoun = "338,356,309,262"
 gordalfortress = "548,378,423,290"
 gulrok = "165,364,278,270"
 zangarra = "713,35,287,277"
 orunaicoast = "427,0,279,267"
 telmor = "207,511,497,157"
 courtofsouls = "150,264,307,229"
 tomboflights = "352,271,326,212"
 northgate = "571,0,398,149"
}
unex = true
bW = nil
bH = nil
txIndex = nil
txPixelW = nil
txFileW = nil
txPixelH = nil
txFileH = nil
path = "Interface\Worldmap\talador\"
alpha = 0.4
unExAl = 0.35
(*temporary) = nil
(*temporary) = <table> {
 MiniBlks = 6
 I
AddOns:
  BlizzBugsSuck, v6.1.0.0
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  Accountant, v6.01.60100
  Ace3, v
  Arh, v1.4.3
  AskMrRobot, v20
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucScanData, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.541
  BagBrother, v
  Bagnon, v6.1.5
  Bazooka, vv2.6.0
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  Breeze, vv1.52
  ButtonForge, v0.9.39
  Carbonite, v6.0.1
  CarboniteInfo, v6.0
  CarboniteNotes, v6.0.1
  CarboniteQuests, v6.0.1
  CarboniteSocial, v6.0.1
  CarboniteWarehouse, v6.0.1
  CarboniteWeekly, v6.0.1
  Configator, v5.1.DEV.376(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
  GatherMate2, v1.33.5
  Grail, v068
  HealBot, v6.1.2.0
  HealBotTips, v6.1.2.0
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  MasterPlan, v0.38
  MogIt, v3.5.0
  MogItAccessories, v
  MyBits, v
  NugComboBar, v
  omouse, v0.1.4
  Panda, v6.0.0.49
  Pawn, v1.9.16
  Postal, v3.5.4
  Prat30, v3.5.15      
  Prat30Libraries, v
  QuestCompletist, v104
  Skada, v1.4-30
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TheUndermineJournal, v3.4.20150404
  TipHelper, v5.12.DEV.351(/embedded)
  TomTom, vv60100-1.0.0
  WIM, v3.6.25
  WoWPro, v6.1.1A
  WoWProAchievements, v6.1.1A
  WoWProDailies, v6.1.1A
  WoWProLeveling, v6.1.1A
  WoWProProfession, v6.1.1A
  WoWProWorldEvents, v6.1.1A
  BlizRuntimeLib_enUS v6.1.2.60100 <none>
  (ck=b92)
</code>

**Comment by Rythal** [comment]
Fixed with latest push
