### ISSUE TITLE
Missing zone: The Frozen Sea

### ISSUE THREAD

**Issue by nelegalno** [Rythal/Carbonite#292]
Adding it will fix some of the Northrend problems.

**Comment by samyonair** [comment]
yes it would but this is a blizz bug, wasn't fixed as I researched 

but if you can find map id it could be added I think but Blizz has no data for it to call for the moment

**Comment by nelegalno** [comment]
What I meant was to somehow hardcode the zone so Carbonite won't go bonkers each time you enter it.
