### ISSUE TITLE
Flightpoint I don't have is used in calculation for travelling

### ISSUE THREAD

**Issue by wownob** [Rythal/Carbonite#306]
Example:
I am questing in Northern Stranglethorn having FP at Rebel Camp but not in Fort Livingston.
Next Quest is "Priestess Hu'rala". Activating this quest tells me to fly from Rebel Camp to Fort Livingston which is not possible.

**Comment by DaveJ61** [comment]
I have this problem all the time. Dont quote me on this but I believe this
might be being investigated.

**Comment by Thrumbar** [comment]
Could relate to patch 6.1.0
World Environment and Events
•Flight Path Improvements 
  •Improved the logic used for connecting flight paths. Players are now able to fly through flight points
    that they have not discovered yet if it'll result in a more direct flight path to a destination point.

**Comment by Rythal** [comment]
It should have been fixed last night, It was sort of that update yes which needed new logic applied. The map knows of every node possible, but only shows the ones you can fly to. Before it use to not even know about them if you couldn't get to them. So I added a secondary check to ensure only flightpaths you can reach get used.
