### ISSUE TITLE
Cooking and Fishing Daylies are not put to watch window.

### ISSUE THREAD

**Issue by wownob** [Rythal/Carbonite#315]
Auto Watch New Quests ist put to on.
Normal new quests are put to watch window.
Cooking and Fishing Daylies e.g in Stormwind are not put to watch window.

**Comment by samyonair** [comment]
Please check commit 9b6c5bc32eaf6bf86d26e4221d0492edf9fd058b if it fixes your problem please

**Comment by wownob** [comment]
Problem is fixed - Thank you

Norbert Boenner
boennern@aol.com


-----Ursprüngliche Mitteilung----- 
Von: Lars Christian <notifications@github.com>
An: Rythal/Carbonite <Carbonite@noreply.github.com>
Cc: wownob <Boennern@aol.com>
Verschickt: Sa, 13 Jun 2015 11:45 am
Betreff: Re: [Carbonite] Cooking and Fishing Daylies are not put to watch window. (#315)


 
Please check commit 9b6c5bc if it fixes your problem please
