### ISSUE TITLE
double entry for L["Info"] in Carbonite Info Locales

### ISSUE THREAD

**Issue by samyonair** [Rythal/Carbonite#317]
Hi 

I was translating the last changes from Rythal and found an double entry for L["Info"] in the files

from my understanding L Terms can be used more times in Code 
correct me If I'm wrong

This issue is only minor and could be corrected easily for file size purposes

Greetings

Samyonair

**Comment by atk** [comment]
The later definition will simply overwrite the previous one. The first one can be safely removed.
