### ISSUE TITLE
Error in garrison

### ISSUE THREAD

**Issue by Viterian** [Rythal/Carbonite#328]
Latest version from https://github.com/Rythal/Carbonite
Error as seen by BugGrabber,, on enUS client

22x Carbonite\Carbonite-6.2.0.lua:3730: bad argument #1 to 'find' (string expected, got table)
[C]: in function `find'
Carbonite\Carbonite-6.2.0.lua:3730: in function `Split'
Carbonite\NxMap.lua:8074: in function <Carbonite\NxMap.lua:8057>

Locals:
d = "~"
p = <unnamed> {
 npcId = 51574
 originalParentFrame = NxMap1 {
 }
 0 = <userdata>
 texture = <unnamed> {
 }
 texType = "G"
 questId = 28922
 SetType = <function> defined @Wholly\Wholly.lua:1673
}
TempTable = <table> {
 )111966 = <table> {
 }
 )116737 = <table> {
 }
 %In987 = <table> {
 }
 $H40 = <table> {
 }
 #Map823 = <table> {
 }
 1,58.2,39.1|1,10.7,60.8 = <table> {
 }
 (Weapons Merchant~Gunther Weller = <table> {
 }
 %In867 = <table> {
 }
 132,311,348,357 = <table> {
 }
 2|Horde Flight|Malaka'jin, Stonetalon Mountains|81|70.55|89.39 = <table> {
 }
 M^143502350700^971^b3e41b^Blackrock Deposit = <table> {
 }
 )122712 = <table> {
 }
 0|Neutral Flight|Evergrove, Blade's Edge Mountains|475|61.65|39.6 = <table> {
 }
 0,48.32,74.45 = <table> {
 }
 401,396,233,248 = <table> {
 }
 )115189 = <table> {
 }
 )4341 = <table> {
 }
 0,59.8,54.24 = <table> {
 }
 K^143508947900^948^bc1767^Amorphic Cognitor^2 = <table> {
 }
 )23083 = <table> {
 }
 ^C = <table> {
 }
 I^143503097100^971^4692ac^Entered = <table> {
 }
 )89194 = <table> {
 }
 )6256 = <table> {
 }
 0,78.92,63.68 = <table> {
 }
 $M518 = <table> {
 }
 )118563 = <table> {
 }
 I^143511344500^947^436076^Entered = <table> {
 }
 )109124 = <table> {
 }
 0,33.6,56.1 = <table> {
 }
 1|Alliance Flight|Redemption Rise, Talador|946|63.2|25.8 = <table> {
 }
 2|Horde Flight|Falconwing Square, Eversong Woods|462|46.2|46.7 = <table> {
 }
 2,58.5,59.5 = <table> {
 }
 2,46.6,58.7 = <table> {
 }
 )113791 = <table> {
 }
 #Map43 = <table> {
 }
 2,56.7,34.6 = <table> {
 }
 1,75.74,19.98 = <table> {
 }
 (Reshad's Companion~Percy = <table> {
 }
 2,32.1,66.2 = <table> {
 }
 1|Alliance Flight|Surwich, Blasted Lands|19|46.31|88.72 = <table> {
 }
 )70933 = <table> {
 }
 1,54,82.8 = <table> {
 }
 )89999 = <table> {
 }
 #Map928 = <table> {
 }
 )116334 = <table> {
 }
 )117941 = <table> {
 }
 Paladin Trainer = <table> {
 }
 0,35.6,57.4 = <table> {
 }
 2|Horde Flight|Camp Tunka'lo, The Storm Peaks|495|68.8|50 = <table> {
 }
 )117856 = <table> {
 }
 $H26 = <table> {
 }
 #Map605 = <table> {
 }
 %In993 = <table> {
 }
 )116346 = <table> {
 }
 )115353 = <table> {
 }
 #Map37 = <table> {
 }
 )64399 = <table> {
 }
 )109065 = <table> {
 }
 1,46.8,45.1 = <table> {
 }
 M^143502355200^971^689948^Rich True Iron Deposit = <table> {
 }
 0|Neutral Flight|Ethel Rethor, Desolace|101|39|26.9 = <table> {
 }
 1,29,32.4 = <table> {
 }
 1|Alliance Flight|Gol'Bolar Quarry, Dun Morogh|27|75.8|54.4 = <table> {
 }
 (Blacksmith~Rachelle Black = <table> {
 }
 0,79.58,72.73 = <table> {
 }
 )117854 = <table> {
 }
 %In919 = <table> {
 }
 )61931 = <table> {
 }
 )109693 = <table> {
 }
 2,79.5,58.2 = <table> {
 }
 *92 = <table> {
 }
 )122714 = <table> {
 }
 1|Alliance Flight|Amberpine Lodge, Grizzly Hills|490|31.3|59.1 = <table> {
 }
 )117412 = <table> {
 }
 0|Neutral Flight|Serpent's Overlook, Jade Forest|806|43.1|68.4 = <table> {
 }
 #Map480 = <table> {
 }
 )111992 = <table> {
 }
 #Map478 = <table> {
 }
 $M535 = <table> {
 }
 K^143502161100^949^75d4ec^Iron Enforcer^4 = <table> {
 }
 2|Horde Flight|Throm'Var, Frostfire Ridge|941|31.8|9.6 = <table> {
 }
 )113808 = <table> {
 }
 )21574 = <table> {
 }
 2|Horde Flight|Shrine of Two Moons, Vale of Eternal Blossoms|811|62.65|21.79 = <table> {
 }
 2|Horde Flight|Dawnrise Expedition, Tanaris|161|33.34|77.3 = <table> {
 }
 M^143502356500^971^5bc696^Rich True Iron Deposit = <table> {
 }
 )19223 = <table> {
 }
 )116733 = <table> {
 }
 #Map481 = <table> {
 }
 #Map38 = <table> {
 }
 #Map20 = <table> {
 }
 #Map477 = <table> {
 }
 $H14 = <table> {
 }
 %In687 = <table> {
 }
 2|Horde Flight|Camp Mojache, Feralas|121|75.4|44.3 = <table> {
 }
 0|Neutral Flight|Darktide Roost, Shadowmoon Valley|947|59.8|81.4 = <table> {
 }
 2,12.8,34 = <table> {
 }
 2|Horde Flight|Shadowprey Village, Desolace|101|21.56|74.04 = <table> {
 }
 #Map806 = <table> {
 }
 *119^FA = <table> {
 }
 0,41.3,74 = <table> {
 }
 %In727 = <table> {
 }
 2,37.4,51.9 = <table> {
 }
 2,48.76,45.05 = <table> {
 }
 )115079 = <table> {
 }
 2|Horde Flight|Wor'var, Nagrand|950|83.2|44.6 = <table> {
 }
 )118440 = <table> {
 }
 )1

**Comment by JWMcQuire** [comment]
Since the error message also references Wholly which references Carbonite in Wholly.lua, you may want to update to the latest version of that mod, clear BugSack and reload the UI or restart the game. If the error happens again, then disable Wholly temporarily and see if the error repeats. If it does, then the author of Wholly may want to look into this as well while someone looks into this here.

**Comment by Viterian** [comment]
Sorry for the tardy reply. I am unable to consistently replicate this problem. Once I can find this issue to be consistent then I'll repost the issue.
