### ISSUE TITLE
Bonus quest show in watch as complete when not

### ISSUE THREAD

**Issue by Thrumbar** [Rythal/Carbonite#333]
1. Entering area for bonus quest
2. Bonus quest pops in quest watch
3. Bonus quest shows as complete when no objectives are done

https://onedrive.live.com/redir?resid=50E237CE0C7C122F!14971&authkey=!AHGeUX_SkIIvmmA&v=3&ithint=photo%2cjpg
Edit 1: After reading this post
http://www.wowinterface.com/forums/showpost.php?p=309636&postcount=6
I tried to check a Bonus Task that my characters all have not done with the results in the image below.
https://onedrive.live.com/redir?resid=50E237CE0C7C122F!14996&authkey=!AIxcWXJr2z3ybzk&v=3&ithint=photo%2cjpg
Note that I have both Carbonite Quest (Current Curse) and QuestKing2 installed..

**Comment by Rythal** [comment]
Carbonite does not store objectives nor how far along you are... if it's saying all the steps are complete i'm not sure it's Carbonite over a bug in WoW.

**Comment by Thrumbar** [comment]
Posted this after reseting UI and loading only 
Carbonite Maps
Carbonite Quest
and still getting the Bonus task showing as full but showing correctly using base UI.
No other addons installed.

**Comment by DaveJ61** [comment]
Yes I have this too. The bonus quests are showing as completed, even if I am running through with a completely new character.

**Comment by SteveEbey73742** [comment]
Running NO addons, get same error. Blizzard bug, not carbonite bug.

**Comment by Thrumbar** [comment]
Sorry but regardless if I do a full reset of just unload all the addons the default UI shows the Bonus Task correctly for me while Carbonite does no (shows them as fully done).  Other Quest addons (QuestKing2) shows the task correctly also.

**Comment by samyonair** [comment]
Hi Sorry for late answer, have contacted atk if he can find the failure I have searched for seems to be in NX.quest.lua line 8830 and following lines 

Greetings samyonair

**Comment by Rythal** [comment]
It is now fixed and was rather simple... GetQuestObjectiveInfo () was changed in one of the recent patches to have a third parameter for display completed ... I had thought that meant "still display quests that are completed" (gotta love working with undocumented API) when it actually meant show the quest text as fully completed, soon as I changed both instances to false in the quest code problem went away.
