### ISSUE TITLE
Carb map doesn't follow

### ISSUE THREAD

**Issue by wownob** [Rythal/Carbonite#344]
I use the latest dev version. For all my chars the Carb Map doesn't follow my char. I have to move the map manually. Relog or newstart doesn't help. If I log to another char (even on another Server) the map of my previous char shows up. This is true for the "llttle" and the "big" map. Minimap follows (combined Carb and Blizz).

**Comment by IrcDirk** [comment]
No logs no help.

**Comment by wownob** [comment]
Sorry, was my fault.
