### ISSUE TITLE
Carbonite Map

### ISSUE THREAD

**Issue by LustSinister** [Rythal/Carbonite#357]
First off I deleted everything in my Addons folder as well as my WTF folder. When I went to put the newest push for carbonite which was the master all was fine when I first loged in. Then I went to profiles and there were old profiles there which wasn't the problem. But I went to rest the default profile and this happened. 
![img_03012016_005831](https://cloud.githubusercontent.com/assets/16523313/12077511/4f66d3b4-b1b5-11e5-93aa-2a2384d48b74.png)

(BTW since I deleted everything just wanted to let know that I only put carbonite back in the Addons folder.)

**Comment by Thrumbar** [comment]
I tried to replicate your error but cannot.  I think it may be the location you are at, does the error occur on other characters or if you are in a different zone??

Thrumbar

**Comment by jeffy162** [comment]
Try this: Make sure that you have enabled the option for "Take Map Function Control" on the "Maps" tab of the "Map" page of the Carbonite options. That worked for me, and I didn't even know about that option. Once Rythal told me about it though, it worked great. Carbonite was back to normal.
