### ISSUE TITLE
Carbonite + Combat

### ISSUE THREAD

**Issue by xSimone** [Rythal/Carbonite#361]
Hi I'm wondering.. to make sure, is Carbonite locking down during combat?

If so, how do you turn this off? It's extremely annoying.. I cannot open my raid window when we're on a boss, or drag an ability to my toolbar for specific fights if someone pulled prematurely and so on.

**Comment by Rythal** [comment]
Carbonite locks itself down, nothing else :) so it wouldn't affect your toolbar or raid windows.

**Comment by xSimone** [comment]
Is it possible to STOP it from locking? I've never liked that feature.

**Comment by Rythal** [comment]
Yes there is an option under maps for combat compatability mode... it does it because sometimes depending what other addons your running, trying to do anything with carbonite during combat results in thousands of errors.

**Comment by xSimone** [comment]
Wow, are you serious? Would that result in client crashes? I run like.. 30 other addons like BarTender and Atlas Loot, nothing else major though..

**Comment by Divyrr** [comment]
I'll have to do that. I used to run with my map open, but when I get in combat
I'm stuck with my map open and can't see.


Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.91&pv=5.1.1&source=email_footer_2] On Sat, Jan 23, 2016 at 12:10 PM, xSimone < notifications@github.com [notifications@github.com] > wrote:
Wow, are you serious? Would that result in client crashes? I run like.. 30 other
addons like BarTender and Atlas Loot, nothing else major though..

—
Reply to this email directly or view it on GitHub
[https://github.com/Rythal/Carbonite/issues/361#issuecomment-174209448] .[https://github.com/notifications/beacon/AJfO9nozDtnd-pDvjuT6bjVuNHD3Qe7Pks5pc7mygaJpZM4HK3F8.gif]

**Comment by xSimone** [comment]
Yeah that's the problem I had too, once I couldn't close my friendslist because I pulled a mob.

**Comment by xSimone** [comment]
Also Rythal sorry for being unclear, I'm using the complete Carbonite collection. So Carbonite is apart of my raid windows too.

**Comment by IrcDirk** [comment]
Use compatibilty mode. Works for me ;)

**Comment by Rythal** [comment]
I run with the combat locks off with no problem, and I also use bartender.. it was usually full UI replacements that were causing the problems.

**Comment by xSimone** [comment]
Hold on, am I meant to turn Compatibility mode ON or OFF? I've just turned it ON now, I thought it was SUPPOSED to be OFF.

**Comment by xSimone** [comment]
Okay seems to work, sorry for the false bug report. I've got a couple others to toss up. Thank you so much for helping me out.

**Comment by NotDead** [comment]
Sorry, for writing in closed issue, but I had a question. Is it misspelling in our Options.lua (https://en.wiktionary.org/wiki/compatability)?

**Comment by IrcDirk** [comment]
Yep, there was misspelling there, corrected. Thanks.
