### ISSUE TITLE
Small Bug: Quest UI Minimise overlapped.

### ISSUE THREAD

**Issue by xSimone** [Rythal/Carbonite#363]
http://i.imgur.com/EXFEjft.jpg

It seems the minimise button is overlapped by the 'Show Party Quests' button. 

--- This has been trialed with no other addon running in the background other than the full Carbonite Collection. ---

**Comment by xSimone** [comment]
http://i.imgur.com/LtjDOcO.jpg   Bigger picture for better clarity.

**Comment by DaveJ61** [comment]
I can also confirm this. I just muddled on through thinking that it was a cosmetic issue that would be resolved on a lower priority. It has been in existence for a long, long time and I really can't recall anybody else has pointed this out.

**Comment by IrcDirk** [comment]
Yeah thats here for long time. Will try to fix it.
