### ISSUE TITLE
[ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function '<unnamed>:SetPoint()'.

### ISSUE THREAD

**Issue by Thrumbar** [Rythal/Carbonite#403]
1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function '<unnamed>:SetPoint()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SetPoint'
Carbonite\NxUI.lua:1886: in function `Adjust'
Carbonite\NxUI.lua:3130: in function <Carbonite\NxUI.lua:3082>

Locals:

**Comment by IrcDirk** [comment]
Should be fixed. Please confirm.

**Comment by Thrumbar** [comment]
Have not had issue will test further until then am closing this ticket...
