### ISSUE TITLE
Carbonite.Quests\NxQuest.lua:2715: hooksecurefunc(): SetTradeSkillItem is not a function

### ISSUE THREAD

**Issue by Thrumbar** [Rythal/Carbonite#406]
1x Carbonite.Quests\NxQuest.lua:2715: hooksecurefunc(): SetTradeSkillItem is not a function
[C]: in function `hooksecurefunc'
Carbonite.Quests\NxQuest.lua:2715: in function `Init'
Carbonite.Quests\NxQuest.lua:2060: in function `func'
Carbonite\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:

**Comment by Rythal** [comment]
Same, should be fixed.
