### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by chaossparks** [Rythal/Carbonite#413]
I officially tried EVERYTHING! still getting this error,  I am running Live. Error will not open while using Female Toons! Carbonite is the only addon I try to use. 

Message: Interface\AddOns\Carbonite\NxUI.lua:5864: attempt to call global 'CooldownFrame_SetTimer' (a nil value)
Time: 07/22/16 15:21:11
Count: 20
Stack: Interface\AddOns\Carbonite\NxUI.lua:5864: in function `?'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:9158: in function `UpdateList'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:8611: in function `func'
...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals: self = <table> {
 SelFrm = <unnamed> {
 }
 LineHPad = 0
 MinW = 124
 Vis = 16
 HdrH = 0
 Data = <table> {
 }
 FrmData = <table> {
 }
 Offsets = <table> {
 }
 BaseLineH = 12
 UserFunc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9228
 ShowAll = true
 Selected = 0
 ButData = <table> {
 }
 Strs = <table> {
 }
 ItemFrameScale = 10
 Num = 16
 Columns = <table> {
 }
 User = <table> {
 }
 SSW = 216.0000192523
 Buts = <table> {
 }
 UsedFrms = <table> {
 }
 Top = 1
 Font = "QuestWatch.WatchFont"
 SSH = 208
 Frm = <unnamed> {
 }
 FontObj = NxFontW {
 }
 Sorted = false
 MinH = 1
 ItemFrameAlpha = ".6"
}
showLast = nil
lineH = 13
hdrH = 0
last = 16
strNum = 33
cNum = 3
lfrm = <unnamed> {
 0 = <userdata>
 NxInst = <table> {
 }
 texture = <unnamed> {
 }
}
offX = 3
offY = 3
adjY = 0.5
doBind = true
(for index) = 6
(for limit) = 16
(for step) = 1
n = 6
line = 6
data = "WatchItem~18~133015~0"
typ = "WatchItem"
v1 = "18"
v2 = "133015"
v3 = "0"
f = NxListFrms1 {
 NormalTexture = <unnamed> {
 }
 HotKey = <unnamed> {
 }
 NXListFType = "WatchItem"
 count = 0
 charges = 0
 Count = <unnamed> {
 }
 questLogIndex = 18
 0 = <userdata>
 rangeTimer = -1
 Cooldown = <unnamed> {
 }
 icon = <unnamed> {
 }
}
scale = 0.7
id = 18
start = 0
duration = 0
enable = 1
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = 1
(*temporary) = "attempt to call global 'CooldownFrame_SetTimer' (a nil value)"
L = <table> {
 Fireweed = "Fireweed"
 Dragonblight = "Dragonblight"
 Bloodwatcher Point, Badlands = "Bloodwatcher Point, Badlands"
 Westfall = "Westfall"
 Abyssal Depths = "Abyssal Depths"
 Stormshield = "Stormshield"
 Options have been reset for the new version. = "Options have been reset for the new version."
 Archaeology Blob Transparency = "Archaeology Blob Transparency"
 Map Mouse Button Binds = "Map Mouse Button Binds"
 Shadowmoon Village, Shadowmoon Valley = "Shadowmoon Village, Shadowmoon Valley"
 Opening = "Opening"
 Darnassus = "Darnassus"
 Menus = "Menus"
 Gilneas = "Gilneas"
 Reset global options = "Reset global options"
 Left-Click to Toggle Map = "Left-Click to Toggle Map"
 Imported = "Imported"
 Un'Goro Crater = "Un'Goro Crater"
 Dustwind Dig, Badlands = "Dustwind Dig, Badlands"
 Stygian Bounty, Vashj'ir = "Stygian Bounty, Vashj'ir"
 Kirthaven, Twilight Highlands = "Kirthaven, Twilight Highlands"
 Western Plaguelands = "Western Plaguelands"
 The Jade Forest = "The Jade Forest"
 Middle-Click to Toggle Guide = "Middle-Click to Toggle Guide"
 Large Timber = "Large Timber"
 Shrine of Seven Stars = "Shrine of Seven Stars"
 Max Vendors To Record = "Max Vendors To Record"
 Crypt of Forgotten Kings = "Crypt of Forgotten Kings"
 Left click toggle Map = "Left click toggle Map"
 Flamestar Post, Burning Steppes = "Flamestar Post, Burning Steppes"
 Sets the action performed when middle clicking holding CTRL = "Sets the action performed when middle clicking holding CTRL"
 Report Status = "Report Status"
 Winterspring = "Winterspring"
 Main Options = "Main Options"
 Flying = "Flying"
 Com %d Bytes sec %d = "Com %d Bytes sec %d"
 Darkshore = "Darkshore"
 Dark Heart of Pandaria = "Dark Heart of Pandaria"
 Paladin Trainer = "Paladin Trainer"
 Small Font = "Small Font"
 Frostweed = "Frostweed"
 Show Received Levelups = "Show Received Levelups"
 Gold Vein = "Gold Vein"
 Onyxia's Lair = "Onyxia's Lair"
 Apexis Excavation, Spires of Arak = "Apexis Excavation, Spires of Arak"
 When enabled, the full size

**Comment by JWMcQuire** [comment]
Please list step-by-step what you tried so we can see if you missed anything. Also list all the addons you have active.

**Comment by chaossparks** [comment]
Sure thing, first I figured I must be using another add on that was crashing it so I got ride of all Addons. After that I deleted all carbonite files and reinstalled.  When I received the same error I turned to the forums where I got a link for the master file from this website and downloaded from the link, still received the same error. Rythal himself was said I must not be using the git file that was pushed out wed.  So again I deleted all carbonite files and even deleted my WTF file just for laughs. I then proceeded to this site looked up the file from here hit download opened up the file and copied all said files besides of course the two files that's wasn't needed and paste it into my Addons file in wow directory. Again error popped up.   I made two test toons one male and the other female no error popped up. Used my main toon as always error pop up.  Cried alittle and a short to the point  Prayer and still a pop up.

**Comment by JWMcQuire** [comment]
Thanks for replying. Rythal also said that error is one of the first ones he fixed, so my next step is to try to see if I can duplicate your error. It is really strange that it only happens on your female toons and not the males. That may or may not help us, but anything is possible.

Since I have 2 females, one Draenie and one Human, I'll log into those with a clean bug sack and see if anything comes up.

For now as a shot in the dark, do any of your female toons have any quest related items in their bags or banks that your male toons don't? 

Another question I have that might be considered a "bone-head" question on my part is, do you have the Blizzard client set to automatically update WoW, and have you let it finish downloading and installing the pre-patch?

**Comment by chaossparks** [comment]
YES! you are the MAN!  I got rid of quest items in my bag and no more errors across all toons!  thanks so much for helping out! thank you, thank you, thank you! PLEASE tell me how I can donate Rythal!

**Comment by JWMcQuire** [comment]
You are very welcome! Glad I could help :)
