### ISSUE TITLE
Login bug dealing with Carbonite.Quests

### ISSUE THREAD

**Issue by ska737** [Rythal/Carbonite#418]
Logged in with a  character, the following popped up:

Date: 2016-07-23 12:27:36
ID: 67
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 2715:
   hooksecurefunc(): SetTradeSkillItem is not a function
Debug:
   [C]: ?
   [C]: hooksecurefunc()
   Carbonite.Quests\NxQuest.lua:2715: Init()
   Carbonite.Quests\NxQuest.lua:2060: func()
   ...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:55:
      ...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:48
Locals:

AddOns:
  Carbonite, v6.2.0
  CarboniteInfo, v6.2.0
  CarboniteQuests, v6.2.0
  CarboniteSocial, v6.2.0
  CarboniteWarehouse, v6.2.0
 ... A lot of other ones... If needed, can supply.

**Comment by JWMcQuire** [comment]
Rythal fixed this error already, so you will need to download and install the latest version from here: https://github.com/Rythal/Carbonite/archive/master.zip
