### ISSUE TITLE
Bonus quest error in Draenor

### ISSUE THREAD

**Issue by jcmgamer** [Rythal/Carbonite#419]
Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:8669: Usage: GetTaskInfo(questID)
Time: 07/24/16 22:26:17
Count: 20
Stack: [C]: ?
[C]: in function `GetTaskInfo'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:8669: in function `UpdateList'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:8449: in function `func'
Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:55: in function <Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals: 

For some reason the error window isn't letting me copy the addons I'm using at the time of the crash.  All addons are updated to the latest available working copy

Addons:
AddonSkins, AtlasLoot, Auditor 2, blockchinese, carbonite 7.0.0, clique, _corpse, DeadlyBossMods, Elvui, Kui Nameplates, Masterplan, omen, omnicc, pawn, postal, skada, the undermine journal, tip tac, tradeskillmaster, xct+

Libraries:
ace3, qtip1.0, sharedmedia 3.0

**Comment by SteveEbey73742** [comment]
getting same bug, but if you disable quest watch of bonus objectives, and enter the area, no error.  the carbonite quest log shows the bonus quest, and you can complete it.

**Comment by JWMcQuire** [comment]
Which bonus quest or quests are you doing when this error pops up, and where in Draenor does it happen?

Install bug sack and bug grabber (both must be used together) or bug swatter. They make it easier to copy error log info when one pops up.

**Comment by JWMcQuire** [comment]
Note: This error only pops up when attempting Bonus Quests in Draenor, but not in Tanaan which still works as expected.

**Comment by jcmgamer** [comment]
I was getting the error in Frostfire, Gorgorond, Talador, and Spires.  Nagrand for some reason didn't have any issues.

**Comment by SteveEbey73742** [comment]
Nagrand and Shadowmoon overlap with Hellfire Peninsula, so that may be why. The code seems to die when trying to identify the questid, as it comes up on the bonus task.  wonder if a loop, until the function isBonusTask() returns true, would help.

**Comment by IrcDirk** [comment]
Should be fixed. Confirm.
