### ISSUE TITLE
Broken Transparency and Scale settings on Map/Minimap

### ISSUE THREAD

**Issue by IrcDirk** [Rythal/Carbonite#421]
As on this screenshot:

![Screenshot](http://i.imgur.com/Z3IjZku.png)

Text is overflowing box and there is no scroller.

**Comment by jeffy162** [comment]
There is no graphical representation of a "scroller', but you can still scroll the settings. The right click Cabonite map settings have been like this since before Legion, but, they work. At least in WoD we had a scroll-bar to see the adjustment moving. Now there isn't even that.

**Comment by Cheilynn** [comment]
My quest log looks like that too, but I found that if you enlarge the window, the quest box enlarges too.

**Comment by IrcDirk** [comment]
Both things fixed im my pull request, waiting till rythal will push it to master.
