### ISSUE TITLE
Quest Blog Transparency

### ISSUE THREAD

**Issue by jessepink** [Rythal/Carbonite#426]
The transparency on the map/minimap seems to be broken-- even though it is set to 0.30 it appears that it is at 1.

![image](https://cloud.githubusercontent.com/assets/2281470/17237185/c03e16e4-5514-11e6-9d60-6144bb39b332.png)

**Comment by jeffy162** [comment]
At least you get quest blobs. They only show on my minimized map when they are not tracked. As soon as you hit the "Auto Track" (the purple button on the quest watch header) button, they go away, **SOMETIMES** they show up when I mouse over the map, but, not very often. Hopefully Rythal and "the team" will have this straightened out for the Legion release. After all, this is a pre-patch version of WoW (on live) and it's just not right yet. It's got plenty of bugs and I've seen some missing stuff, too. Well, missing when compared to "normal".
