### ISSUE TITLE
Incorrect Map Placement in Dungeons

### ISSUE THREAD

**Issue by Viusing** [Rythal/Carbonite#428]
In almost every dungeon I've ran since the update the map placement is off, or the floor is wrong, or both.

**Comment by DaveJ61** [comment]
I have also noticed this.

**Comment by JWMcQuire** [comment]
I just used the Carbonite Map guide to set the waypoint to Carbonite's coordinates for Utgarde Keep, and it was right on the nose.

So are you talking about the placement of quest objectives in the instances or actual locations such as I just tested?

**Comment by DaveJ61** [comment]
As I said. I was in the keep.

**Comment by Viusing** [comment]
@JWMcQuire Try actually visiting a dungeon. Plotting coords to a dungeon has nothing to do with placement whilst in a dungeon...

**Comment by Viusing** [comment]
In case "map placement" wasn't descriptive enough, I was describing the map overlay as it is combined with the built in wow minimap. The "plqcement" of said map is way off in all the dungeons I've visited. Often resulting in blank carbonite maps as it places the map (and thus my coords) way off the visible border of the dungeon's map.

**Comment by JWMcQuire** [comment]
@DaveJ61 Thanks for clarifying that. 

@Viusing lol My response was based on your use of the phrase "map placement" which lead me to ask for clarification. You didn't specify inside or outside or actual dungeon location. The more info provided the more likely people trying to help will know how to approach the issue.

Also, you posted while I was writing a response. I did actually go into the dungeon and saw what you are talking about. I have been in a few dungeons, but never really paid attention to the map as I was following the rest of the group.

@Viusing I just saw your post, so thanks for that and the more detailed explanation. Hopefully a future update will correct this issue.

**Comment by DaveJ61** [comment]
@Viusing I understood your comment as I have experienced this myself. It was sort of like when your using your satnav on a new road and the maps have not been updated. You seem to be in the middle of a field.

**Comment by Viusing** [comment]
Fixed by recent commit by @Rythal.

Kudos.

**Comment by Rythal** [comment]
i need samples of which ones so I can visit them and find out why the function fails.

**Comment by Viusing** [comment]
Escape From Durnholde Keep was a recent one

**Comment by Rythal** [comment]
should be fixed... I hope
