### ISSUE TITLE
Error when opening the Warehouse

### ISSUE THREAD

**Issue by JWMcQuire** [Rythal/Carbonite#445]
Version: Latest version of Carbonite as of 8/8/2016
WoW Version: Legion 7.0.3

Error pops up first when I open the Warehouse and continues each time I loot, sell, or take/put items into my bank or Guild bank after that.
If I don't open the warehouse, the error doesn't pop up.

23x Carbonite\NxUI.lua:3934: Usage: <unnamed>:SetColorTexture(red, green, blue[, alpha])
[C]: in function `SetColorTexture'
Carbonite\NxUI.lua:3934: in function `Update'
Carbonite\NxUI.lua:3567: in function `SetPressed'
Carbonite\NxUI.lua:5768: in function `Update'
Carbonite.Warehouse\NxWarehouse.lua:2115: in function `UpdateItems'
Carbonite.Warehouse\NxWarehouse.lua:1817: in function `Update'
Carbonite.Warehouse\NxWarehouse.lua:1214: in function `Create'
Carbonite.Warehouse\NxWarehouse.lua:1364: in function `ToggleShow'
Carbonite.Warehouse\NxWarehouse.lua:3438: in function `func'
Carbonite\NxUI.lua:7126: in function `UserFunc'
Carbonite\NxUI.lua:3718: in function <Carbonite\NxUI.lua:3702>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 968998
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil

Addons:
Carbonite
Carbonite.Items 
Carbonite.Notes 
Carbonite.Quests
Carbonite.Social
Carbonite.Warehouse 
Carbonite.Weekly
GatherMate2_Data_Carbonite 
LevelFlight
MicroDeclineDuel 
Scrap
Scrap_Merchant: 
Scrap_Options
Scrap_Spotlight
Scrap_Visualizer
Garrison Mission Manager
GuildDonationHelper 
Bartender4
Skada

**Comment by IrcDirk** [comment]
I think Rythal fixed it. Try newer version from git with latest commit.

**Comment by JWMcQuire** [comment]
Thanks for the suggestion, IrcDirk. Rythal had actually pushed the latest update just a couple of hours after I updated from the last commit. So I hadn't updated from that yet. 

Anyway, after merging, pulling, and syncing with Rythal's master and updating my in-game version from that, I can confirm that Rythal's latest commit fixed this issue. :-)
