### ISSUE TITLE
7.3 Warehouse Not Showing Bank Items

### ISSUE THREAD

**Issue by spectr1701** [Rythal/Carbonite#446]
After installing the latest version of Carbonite and its modules (7.3), Warehouse isn't showing any items that are in my characters' banks.  I have visited the banks, opened all of my bags, and my character screen to register the contents into Warehouse, but only items that are in my bags or on my character screen show up.  Nothing from my bank and its bags are registered.  I have cleared the .lua files to totally reset the addon and that didn't even help.

**Comment by Rythal** [comment]
Anyone else able to confirm this issue? I've been trying but my bank items are all showing up in the tooltips and in the warehouse listing, both current character and alts.

**Comment by JWMcQuire** [comment]
I can see the bank items and do a search and see that they are in the bank instead of my bags. So that is at least okay since installing the latest version as of today 8/13.

However, the items in my reagent banks aren't showing up.

**Comment by spectr1701** [comment]
Here is a screenshot of my bag contents:

![screen shot 2016-08-19 at 10 17 29 am](https://cloud.githubusercontent.com/assets/20939094/17812736/6a578d62-65f6-11e6-8e03-3af6c5f73c0a.png)

Here is a screenshot of my Carbonite Warehouse:

![screen shot 2016-08-19 at 10 17 51 am](https://cloud.githubusercontent.com/assets/20939094/17812764/8a7eae22-65f6-11e6-8ea7-f0e4da9355af.png)

As you can see, my bag items are not in my warehouse.

**Comment by Rythal** [comment]
Erm.. I see all your bag items listed there...

10 Herb Baked Egg
20 Wool Bandage
Arclight Spanner
Blacksmith Hammer
Strong Fishing Pole
etc etc... 

Unless i'm misunderstanding what you mean by bag items not showing up.

**Comment by spectr1701** [comment]
The linen cloth, silk cloth, copper bars...the items that are in my bank, not my bags.

**Comment by Rythal** [comment]
Ok that makes more sense :) and matches what JW was saying, crafting supplies are not showing in the list.. no matter bags, bank or reagent bank. I'll look into it after work.

**Comment by JWMcQuire** [comment]
After the latest commits, the crafting items now show up as intended. Thanks. :-)
