### ISSUE TITLE
Carbonite.Quests\NxQuest.lua - GetTaskInfo(questID)

### ISSUE THREAD

**Issue by DaveJ61** [Rythal/Carbonite#448]
Made a demon hunter this morning but it's unplayable with carbonite due to the the following error every second or so. Carbonite works fine elsewhere... and now 'quest complete' isn't working again... grrr:-

63x Carbonite.Quests\NxQuest.lua:8670: Usage: GetTaskInfo(questID)
[C]: in function `GetTaskInfo'
Carbonite.Quests\NxQuest.lua:8670: in function `UpdateList'
Carbonite.Quests\NxQuest.lua:8450: in function `func'
Ace3\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:
(*temporary) = nil

**Comment by IrcDirk** [comment]
Can confirm this error, but mine is showing when i set goto on quest objective, then hovering on different zone than quest in Dreanor (WOD).

**Comment by IrcDirk** [comment]
Should be fixed now. Please confirm.

**Comment by BlueChimera** [comment]
I can confirm this fixed the bonus quest lua errors I was getting.
