### ISSUE TITLE
1x Carbonite.Quests\NxQuest.lua

### ISSUE THREAD

**Issue by samyonair** [Rythal/Carbonite#45]
Current State 6.0 Rythal/Carbonite

Questing Apix Crystal Daily 

1x Carbonite.Quests\NxQuest.lua:5646: script ran too long
Carbonite.Quests\NxQuest.lua:5494: in function `HideUIPanel'
Carbonite.Quests\NxQuest.lua:2622: in function <Carbonite.Quests\NxQuest.lua:2619>
[C]: in function `HideUIPanel'
Carbonite.Quests\NxQuest.lua:5646: in function `UserFunc'
Carbonite\NxUI.lua:2681: in function `Notify'
Carbonite\NxUI.lua:3089: in function `UserFunc'
Carbonite\NxUI.lua:3594: in function <Carbonite\NxUI.lua:3578>
Carbonite.Quests\NxQuest.lua:5646: in function `UserFunc'
Carbonite\NxUI.lua:2681: in function `Notify'
Carbonite\NxUI.lua:3089: in function `UserFunc'
Carbonite\NxUI.lua:3594: in function <Carbonite\NxUI.lua:3578>

Locals:
self = <table> {
 TitleFStr = <table> {
 }
 BorderW = 7
 BorderH = 7
 ButClose = <table> {
 }
 CursorIsSet = false
 Border = true
 BackgndAlphaDiff = 0.35
 BackgndAlphaMin = 0.65
 Events = <table> {
 }
 UserFunc = <function> defined @Carbonite.Quests\NxQuest.lua:5643
 BackgndFadeOut = 0.75
 SaveData = <table> {
 }
 ButMaxer = <table> {
 }
 TitleH = 12
 TitleLineH = 10
 Maxer = true
 Closer = true
 User = <table> {
 }
 LayoutMode = ""
 MovSizing = false
 BackgndFadeTarget = 1
 TopH = 19
 ChildFrms = <table> {
 }
 BackgndFadeIn = 1
 Name = "NxQuestList"
 Frm = NxQuestList {
 }
 BackgndFade = 1
 TitleLines = 1
 ButW = 30
 Sizeable = true
}
name = "Close"

**Comment by atk** [comment]
I have fixed all calls of FindCurByIndex so that no index below 0 should ever be requested internally...
