### ISSUE TITLE
Bonus Quest shows up twice

### ISSUE THREAD

**Issue by JWMcQuire** [Rythal/Carbonite#461]
Version: Latest version of Carbonite as of 8/16/2016
WoW Version: Legion 7.0.3
Issue: Double listing in Quest watch of the Bonus Quest #39279, "Assault on Mardum" which shows up after turning in the first quest in Despair Ridge. This issue only happens with this quest.

No Error, just an issue with the bonus quest showing up twice in the quest watch.

While adding the DH starting quests, I experienced an issue with the above mentioned bonus quest showing up twice in the quest watch window even before I added it to the database. Since Carbonite has been updated since I created the Demon Hunters I used to add the DH starting area, I created one more just to see if the latest update fixed this issue, but it didn't. The following screen shot illustrates the issue.

![double bonus quest in dh start](https://cloud.githubusercontent.com/assets/12398481/17719018/171f3e58-63dd-11e6-8f85-d1e429b7a4db.jpg)

Addons:
Carbonite
Carbonite.Items 
Carbonite.Notes 
Carbonite.Quests
Carbonite.Social
Carbonite.Warehouse 
Carbonite.Weekly
GatherMate2_Data_Carbonite 
LevelFlight
MicroDeclineDuel 
Scrap
Scrap_Merchant: 
Scrap_Options
Scrap_Spotlight
Scrap_Visualizer
Garrison Mission Manager
GuildDonationHelper 
Bartender4
Skada

**Comment by IrcDirk** [comment]
All bonus quests doubles not only in DH area byt in Dreanor too.

**Comment by JWMcQuire** [comment]
Fix confirmed.

Thanks.
