### ISSUE TITLE
Carbonite Map is not showing "Legion invasion events"

### ISSUE THREAD

**Issue by Kabulla** [Rythal/Carbonite#465]
As soon as I disable Carbo, the event shows, including the information on time on the original maps...

**Comment by JWMcQuire** [comment]
You don't need to disable Carbonite, just hold down "alt" and press "M", to bring up the Blizzard map.

**Comment by Kabulla** [comment]
Ok... as it is with me, they don't... will try the "alternative map" approach and come back...

**Comment by Rythal** [comment]
Which parts of Carbontie do you have active and running?

**Comment by Kabulla** [comment]
Usually all of them, today I disabled the Quest part because something started spamming "Quest-Status" into the party chat...

![carbonite_event](https://cloud.githubusercontent.com/assets/20712583/17840189/74fb8646-67ff-11e6-8b1f-1ca69d819f3e.jpg)

**Comment by JWMcQuire** [comment]
@Kabulla  To stop the party chat quest updates, go into the quest module on the first page and under "Quest Options", un-tick "Share Quest progress". This should stop the party chat quest update info from showing up.

@Rythal After checking to make sure I my game version was up to date with the Master version, I went into the game to confirm whether I could see the invasion events in Carbonite's map. Unfortunately, they don't show up. Even after playing around with transparency, I still couldn't get the invasions to show up. Here are a couple of screenshots.
![blizmap_invasion](https://cloud.githubusercontent.com/assets/12398481/17841984/cfd4bfea-67e3-11e6-920e-5966dd6a8f4c.jpg)
![carb_no invasion](https://cloud.githubusercontent.com/assets/12398481/17841989/d838525a-67e3-11e6-8403-a8cf98ecf56a.jpg)

Is it possible that you haven't pushed the edit that adds the invasion events to the map to Git yet?

**Comment by Rythal** [comment]
It's pushed... i've been trying to get mine to not show and I can't, so consider me lost.. The only option that modifys the invasions is Icon Scale under map, growing and shrinking the size of the icon... besides that I went through every option I could possibly find and turned them on or off and did reloads, and the invasions always showed.

**Comment by Rythal** [comment]
well fuck me... no it wasn't pushed, i've been doing commits and fixes every day but my local git wasn't pushing them when I hit commit.

**Comment by JWMcQuire** [comment]
lol I use the desktop app, and until about two updates ago, my commits were automatically syncing when I pushed a commit. Now I have to push sync to get my local to Git.

**Comment by Rythal** [comment]
That's exactly what happened to me... up until this week it always sync'd when I pushed

**Comment by JWMcQuire** [comment]
Yep, and I couldn't find a setting to get it to automate syncing.

Anyway, after updating after your pushes and increasing my icon size in options, I am now able to see the invasions on Carbonite's map. Thanks. :-)
