### ISSUE TITLE
Error entering darkmoon

### ISSUE THREAD

**Issue by wownob** [Rythal/Carbonite#85]
Date: 2014-12-07 08:19:43
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 6422:
   attempt to perform arithmetic on a nil value
Debug:
   Carbonite\NxMap.lua:6422: UpdateOverlay()
   Carbonite\NxMap.lua:6253: UpdateZones()
   Carbonite\NxMap.lua:4501: Update()
   Carbonite\NxMap.lua:3749:
      Carbonite\NxMap.lua:3674
Locals:
self = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 TargetNextUniqueId = 1
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 176.40000718521
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.89999997615814
 Zone = 0
 WorldAlpha = -1.#IND
 StartupShown = true
 ScaleDraw = 0.82870807608672
 BackgndAlphaFade = 1
 MoveLastX = 5866.9544857109
 PlyrDir = 176.40000718521
 PlyrSpeedCalcTime = 2257.232
 MapPosYDraw = 1708.5792064954
 PlyrSpeed = 0
 MapScale = 0.082705396815042
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 214.1244354248
 MMGathererUpdateDelay = 1
 MMAddonFrms = <table> {
 }
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 220.00003051758
 MMScales = <table> {
 }
 MMArrowName = "Interface\Minimap\MinimapArrow"
 MapPosX = 5866.9544857109
 BackgndAlphaTarget = 1
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.81
 H = 141
 Tick = 32116
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 1708.5792064954
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 5866.9544857109
 QuestAlpha = 0.3
 CurWorldUpdateOverlayNum = 1
 MMZoomChanged = false
 Scale = 0.82870807608672
 Targets = <table> {
 }
 BackgndAlpha = 1
 CurOverlaysTexFolder = "elwynn"
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = -1
 UpdateMapID = -1
 MMOwn = true
 MMModels = <table> {
 }
 Size1 = 0.83333335540913
 ShowUnexplored = false
 Arch = <unnamed> {
 }
 PIconMenu = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 IconFrms = <table> {
 }
 StepTime = 0
 PlyrSpeedX = 5866.9544857109
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.1
 ScaleDrawW = 1.2066975438711
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 Win = <table> {
 }
 InstanceId = false
 RealScale = 0.82870807608672
 Data = <table> {
 }
 TrackDir = false
 MMMaskName = "Interface\Buttons\White8x8"
 TrackETA = false
 BGIconMenu = <table> {
 }
 CurOverlays = <table> {
 }
 MMFScale = 0.65517209459308
 MMScale = 0.82870807608672
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 MMZoomType = 0
 Indoors = false
 TextScFrm = <unnamed> {
 }
 MapPosY = 1708.5792064954
 GIconMenuIFindNote = <table> {
 }
 TextFrm = <unnamed> {
 }
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 RMapId = -1
 PlyrY = 1708.5792064954
 Cont = 90
 Tracking = <table> {
 }
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Level = 26
 PlyrRZY = 69.290840625763
 W = 150
 CurWorldUpdateMapId = 30
 MapsDrawnFade = <table> {
 }
 DotRaidScale = 1
 ContFrms = <table> {
 }
 PlyrSpeedY = 1708.5792064954
 TileFrms = <table> {
 }
 ScaleW = 1.2066975438711
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 MMAlphaDelay = 0
 MMOwnedFrms = <table> {
 }
 MMChkDelay = 30
 ArchAlpha = 0.3
 MapIndex = 1
 MapPosXDraw = 5866.9544857109
 PlyrRZX = 41.782158613205
 KillShow = false
 MenuIMonitorZone = <table> {
 }
 NeedWorldUpdate = true
 TransMenu = <table> {
 }
 GIconMenu = <table> {
 }
 Frm = <unnamed> {
 }
 MoveDir = 180
 DotZoneScale = 1
 BackgndAlphaFull = 1
 DotPalScale = 1
}
mapId = -1
bright = 1
noUnexplored = nil
wzone = <table> {
 1 = 1
 2 = 0
 3 = 0
}
txFolder = "elwynn"
overlays = <table> {
 westbrookgarrison = "116,355,269,313"
 fargodeepmine = "240,420,269,248"
 northshirevalley = "355,138,295,296"
 goldshire = "247,294,276,231"
 crystallake = "417,327,220,207"
 towerofazora = "529,287,270,241"
 stonecairnlake = "552,186,340,272"
 stromwind = "0,0,512,422"
 ridgepointtower = "708,442,285,194"
 eastvaleloggingcamp = "703,292,294,243"
 jerodslanding = "396,430,230,206"
 brackwellpumpkinpatch = "532,424,287,216"
}
unex = true
bW = nil
bH = nil
txIndex = nil
txPixelW = nil
txFileW = nil
txPixelH = nil
txFileH = nil
path = "Interface\Worldmap\elwynn\"
alpha = 1
unExAl = 0.35
(*temporary) = nil
(*temporary) = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GI
AddOns:
  BlizzBugsSuck, v6.0.2.1
  MoncaiCompare, v6.0.2
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  Altoholic, v5.4.008
  ArkAutoLootBoP, v11300
  ArkInventory, v30416
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucScanData, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.500
  Bartender4, v4.6.5
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  BrokerRestFu, v60000-1
  Carbonite, v6.0
  CarboniteInfo, v1.0
  CarboniteNotes, v1.1
  CarboniteNotesSample, v1.0
  CarboniteQuests, v1.0
  Chatter, v1.4.5
  Configator, v5.1.DEV.376(/embedded)
  DataStore, v6.0.001
  DataStoreAchievements, v6.0.001
  DataStoreAgenda, v6.0.001
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, v6.0.001
  DataStoreContainers, v6.0.001
  DataStoreCrafts, v6.0.001
  DataStoreCurrencies, v6.0.001
  DataStoreInventory, v6.0.001
  DataStoreMails, v6.0.001
  DataStorePets, v6.0.001
  DataStoreQuests, v6.0.001
  DataStoreReputations, v6.0.001
  DataStoreSpells, v6.0.001
  DataStoreStats, v6.0.001
  DataStoreTalents, v6.0.001
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  FBBroker, v1.20c
  FBOutfitDisplayFrame, v1.4e
  FishingBuddy, v1.4m
  GatherMate2, v1.33.3
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  LightHeaded, v375
  LightHeadedDataA, v375
  LightHeadedDataD, v375
  LightHeadedDataE, v375
  LightHeadedDataQIDNames, v375
  MicroDeclineDuel, vv6.0
  OmniCC, v6.0.10
  Postal, v3.5.1
  Skillet, v
  SlideBar, v5.21c.5521 (SanctimoniousSwamprat)
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  SunnArt, v3.70
  TipHelper, v5.12.DEV.351(/embedded)
  Titan, v5.4.1.60000
  TitanClock, v5.4.1.60000
  TitanPerformance, v5.4.1.60000
  TitanRepair, v5.4.1.60000
  TitanSpeed, v6.0.001
  TitanXP, v5.4.1.60000
  TomTom, vv60000-1.0.1
  WoWPro, v6.0.3G
  WoWProAchievements, v6.0.3G
  WoWProDailies, v6.0.3G
  WoWProLeveling, v6.0.3G
  WowProProfession, v6.0.3G
  WoWProWorldEvents, v6.0.3G
  XPerl, v3.7.5
  XPerlArcaneBar, v
  XPerlParty, v
  XPerlPartyPet, v
  XPerlPlayer, v
  XPerlPlayerBuffs, v
  XPerlPlayerPet, v
  XPerlTarget, v
  XPerlTargetTarget, v
  BlizRuntimeLib_deDE v6.0.3.60000 <none>
  (ck=e29)

**Comment by atk** [comment]
I'll be able to test that on sunday...

**Comment by wownob** [comment]
I had this error again this morning entering Darkmoon. I have the 
release version installed.

Norbert Boenner
boennern@aol.com


-----Ursprüngliche Mitteilung-----
Von: Alex Lohr <notifications@github.com>
An: Rythal/Carbonite <Carbonite@noreply.github.com>
Cc: wownob <Boennern@aol.com>
Verschickt: Fr, 2 Jan 2015 8:01 pm
Betreff: Re: [Carbonite] Error entering darkmoon (#85)


I'll be able to test that on sunday...

**Comment by atk** [comment]
Cannot reproduce this error.
