### ISSUE TITLE
wandering HUD

### ISSUE THREAD

**Issue by SteveEbey73742** [Rythal/Carbonite#89]
![wowscrnshot_121114_154608](https://cloud.githubusercontent.com/assets/3675551/5402867/6ed163ca-814d-11e4-8e11-18727950f9c4.jpg)
![wowscrnshot_121114_154811](https://cloud.githubusercontent.com/assets/3675551/5402878/86594bde-814d-11e4-98a1-2908f5d39b4b.jpg)

Ok, elvui is not the problem. Nagrand questing, tracking quest, arrow moves as I turn during combat. all addons disabled again, to see if it is something else. will post here, with updates.  All addons off, modules loaded are main, quest and warehouse. after combat arrow races off one or the other side of the screen. reload resets it.

**Comment by IrcDirk** [comment]
Happend to me too, but the problem is Zygor i think, disabling it all works good.

**Comment by SteveEbey73742** [comment]
I am not running zygor.  all my other addons were off.

**Comment by Thrumbar** [comment]
Hey all. me again with my magical youtube vids.  Had the tracking hud arrow do a vanishing act on me as of 1/15/2015 using the latest git download as of 01/14/2015.  Watch the entire vid as I show settings and addons I have active.

http://youtu.be/182eJwIQTKk

**Comment by DaveJ61** [comment]
Hi. I noticed in your settings that the HUD arrow setting is not locked. What happens if you lock it.
Also I noticed that you still have one addon other than Carbonite running, Hydra for multiboxing.
Have you tried it without Hydra?

**Comment by Thrumbar** [comment]
Tried with nothing but Carbonite active and with hud locked.  it raced off the screen even faster than first time.  This time it did not move to the left but right away raced off the right side of the screen.

**Comment by DaveJ61** [comment]
Hmmmm.. It might be a good idea to show us a video of that failing without any addons at all.

**Comment by SteveEbey73742** [comment]
Hello all.  In the two pictures posted above, the only addons active are carbonite.  The hud arrow disappeared after my battle, and death.  I did not even have a corpse arrow to follow.  There is also a forum post on the carbonite wow interface forum, that has a small macro, to reset the hud window, so others are having the same issue, to the extent that a workaround to reset it has been created.

**Comment by Rythal** [comment]
The problem is none of us developers are ever seeing this happen, and out of users only 2-3 have said it happens to them. It's extremely difficult to find out why something is happening when there is no errors, and none of us can reproduce it.

**Comment by SteveEbey73742** [comment]
It seems to happen, after the quest complete message is played.  it happens at random, when entering combat, and dependent on which way you turn from aggro, as to the direction it moves.

**Comment by Thrumbar** [comment]
Updated my comment as of 11 hours ago from this post with new vid of no addons installed after deleting wtf and addons folder.

**Comment by Thrumbar** [comment]
It appears that the wandering hud arrow is linked to where the arrow is placed on the screen.  In my case the area above the chat box in the lower left area of the screen.  When it was placed in other areas it did not happen (arrow leaving screen).  See vid, it is long like 8 min and has scrolling event in chat window.

http://youtu.be/8z9jaeN1AP0

It will take some time to upload so if it does not work yet then it has not finished uploading.  Will remove this when I see upload is done

**Comment by SteveEbey73742** [comment]
No, the window placement has nothing to do with it.  It wanders, at random, from anywhere it is put. Using the reset layout, and locking it in place makes no difference at all.  I may go hours into game play, before it wanders, but once it starts, it continues from that point until I log.

**Comment by atk** [comment]
Have you tried to rename WTF folder to WTF.bak (thus actually removing the settings)?

**Comment by SteveEbey73742** [comment]
yes, been there, done that, got the t-shirt.  went completely naked, as it were, on a different computer altogether, and even virus and spyware scanned all my computers.  I build custom gaming rigs for people and spend time on WoW testing the rigs, before shipping them.

**Comment by SteveEbey73742** [comment]
Hope this helps. video taken in icecrown, with auto track turned on, no other addons running. Used the workaround macro to reset the arrow, after the first wander off screen.

http://youtu.be/LLuLc_p1phg

**Comment by Ghosthree3** [comment]
Just found out /reload actually fixes the issue and the arrow returns to normal. So I guess however it's being moved it's not being saved?

**Comment by SteveEbey73742** [comment]
reload does reset to the original layout, and the macro /carb winpos nxhud 150 150 resets the arrow, without reloading.  I have used both methods, and am hoping the error can be found, and eliminated.

**Comment by Watersgrace** [comment]
I have the same problem.  I think more people have this issue than what may be realized.  I know I only just now found a place to post about it that seemed to be monitored recently.  This really is the only problem I have experienced with Carbonite.  I /reload and the arrow comes back, but then shortly after entering combat the arrow will race off the right side of the screen and vanish.

I have done the same as the above poster, turning off all addons except for Carbonite and the issue remains.  It does seem to only happen when entering combat, and even then its not every single time.

I am using the latest download from Github. And I am only using the Carbonite and Carbonite.Quests portions of the addon.

**Comment by SteveEbey73742** [comment]
Using DEV pull, as of May 11, 2015, and problem still exists.  Happens most often in Nagrand.  Set a map point to a treasure node, and as I travel past some talbuks, take aggro. The hud moves to the right, completely off screen.  as I run, I change direction, and the hud pauses near the edge of the screen, but once I change direction again, it is gone.

**Comment by Thrumbar** [comment]
I have fount that if I switch quest I was tracking the tracking arrow would either stop, slowdown or speed up as it moved horizontally across the screen.  This worked on and off.

http://youtu.be/70Fxr2reZUE

**Comment by Thrumbar** [comment]
As of the Wandering Window patch the HUD still flies.  


 ViewView the whole file at version 391ddab  

Carbonite/NxUI.lua  
 
2655 2655     
2656 2656   		local data = self.SaveData  
2657 2657     
2658   ---		if self.Name == "NxInfo1" and mode == "_" then  
2658  +--		if self.Name == "NxHUD" and mode == "_" then			  

This part is remed out and not being parced so I do not see what effect it would have.  But the fix did not stop the Hud from taking a hike off my screen as per my last vid.

**Comment by Rythal** [comment]
It was testing that was left behind... right click tracking hud, reset to defaults, should be fixed from then on.

**Comment by SteveEbey73742** [comment]
IT IS FIXED, THANK YOU TO EVERYONE THAT WORKED ON THIS. I am so happy, no more chasing or reseting the window position.  I have run all 11 toons and it stays put, once i reset and drag it where I want it.  Thank you again.
